### ISSUE TITLE
Migrate splunk modules to extension

### ISSUE THREAD

**Issue by garethgreenaway** [salt-extensions/extension_migration#148]
modules/splunk.py
states/splunk.py

**Comment by nicholasmhughes** [comment]
Add to `saltext-splunk` extension

**Comment by lkubb** [comment]
Since there hasn't been any activity on the already existing repo filled with only boilerplate, I performed the migration using the new saltext-migrate tool myself (for testing purposes, keeping the original answers): https://github.com/salt-extensions/saltext-splunk

It worked very nicely! Migrations are becoming quite straightforward with it.
