### ISSUE TITLE
Migrate consul modules to extension

### ISSUE THREAD

**Issue by garethgreenaway** [salt-extensions/extension_migration#18]
modules/consul.py
states/consul.py

**Comment by cesan3** [comment]
Hello @nicholasmhughes. Could you consider bringing this fix that I pushed here: https://github.com/saltstack/salt/pull/62598, during the migration of the consul module to a salt extension? The PR is closed because of inactivity. I applied the patch locally to my environment, but I forgot that I had a PR opened.
