### ISSUE TITLE
Migrate zookeeper modules to extension

### ISSUE THREAD

**Issue by garethgreenaway** [salt-extensions/extension_migration#180]
modules/zookeeper.py
modules/zk_concurrency.py
states/zookeeper.py

**Comment by nicholasmhughes** [comment]
Add to `saltext-zookeeper` extension

**Comment by lkubb** [comment]
Since there hasn't been any activity on the already existing repo filled with only boilerplate, I performed the migration using the new saltext-migrate tool myself (for testing purposes, keeping the original answers): https://github.com/salt-extensions/saltext-zookeeper

It worked very nicely! Migrations are becoming quite straightforward with it.
